name: testing

on: [push, pull_request]

jobs:
  test_projects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django

    - name: Run Django unit tests
      run: |
        python airline/airline/manage.py test
